#!/bin/bash

export PGUSER="${PGUSER:-trivia}"
export PGPASSWORD="${PGPASSWORD:-theansweris}"
export PGDB="${PGDB:-trivia}"
export PGPORT="${PGPORT:-$( echo "${PG_PORT_5432_TCP_PORT:-5432}" )}"
export PGHOST="${PGHOST:-$( echo "${PG_PORT_5432_TCP_ADDR:-127.0.0.1}" )}"
export PGSSLMODE="${PGSSLMODE:-disable}"
export PGTZ="${PGTZ:-UTC}"

DIR="$( cd "$( dirname "$0" )" && pwd )" 
goose -path=$DIR up
